FROM vscode/devcontainers/base:0-bullseye AS devcontainer

SHELL ["/bin/bash", "-euo", "pipefail"]
WORKDIR /workspace

RUN echo "deb [trusted=yes] https://${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD}@artifactory-bne.silverrail.io/artifactory/Debian-Virtual $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list \
    && apt-get update \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get upgrade -y \
    && apt-get -y --fix-missing install git python3 python3-venv python3-pip bash-completion python-is-python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml gitlab_lint .
RUN python -m pip install --upgrade pip \
    && pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
    && poetry install
